class Imagenes:
    # AMBIENTE
    ARBOL = 'assets/ambiente/Arbol.png'
    COFRE = 'assets/ambiente/cofre.png'
    COLUMNA = 'assets/ambiente/columna.png'
    FUENTE = 'assets/ambiente/fuente.png'
    PIEDRA = 'assets/ambiente/piedra.png'
    PLANTA = 'assets/ambiente/planta.png'

    # FONDOS
    FONDO =  = 'assets/fondos/fondo.png'

    # INVENTARIO
    CRUZ = 'assets/inventario/cruz.png'
    INVENTARIO = 'assets/inventario/inventario.png'

    # ITEMS
    AJUSTES = 'assets/items/ajustes.png'
    COFRE = 'assets/items/cofre.png'
    ULTRABALL = 'assets/items/ultraball.png'

    # MENU
    FLECHA = 'assets/menu/arrow.png'
    CARGAR1 = 'assets/menu/imagenesMenu/cargarEstado1.png'
    CARGAR2 = 'assets/menu/imagenesMenu/cargarEstado2.png'
    CONTINUAR1 = 'assets/menu/imagenesMenu/continuarEstado1.png'
    ICONO = 'assets/menu/imagenesMenu/icono.png'
    JUGAR1 = 'assets/menu/imagenesMenu/jugarEstado1.png'
    JUGAR2 = 'assets/menu/imagenesMenu/jugarEstado2.png'
    MENU1 = 'assets/menu/imagenesMenu/menuEstado1.png'
    MENU2 = 'assets/menu/imagenesMenu/menuEstado2.png'
    SALIR1 = 'assets/menu/imagenesMenu/salirEstado1.png'
    SALIR2 = 'assets/menu/imagenesMenu/salirEstado2.png'

    # ASH
    ASH_DER1 = 'assets/personajes/ash/derecha1.png'
    ASH_DER2 = 'assets/personajes/ash/derecha2.png'
    ASH_DER3 = 'assets/personajes/ash/derecha3.png'
    ASH_FR1 = 'assets/personajes/ash/frente1.png'
    ASH_FR2 = 'assets/personajes/ash/frente2.png'
    ASH_IZQ1 = 'assets/personajes/ash/izquierda1.png'
    ASH_IZQ2 = 'assets/personajes/ash/izquierda2.png'
    ASH_IZQ3 = 'assets/personajes/ash/izquierda3.png'
    ASH_REV1 = 'assets/personajes/ash/reversa1.png'
    ASH_REV2 = 'assets/personajes/ash/reversa2.png'
    ASH_REV3 = 'assets/personajes/ash/reversa3.png'

    # MAESTROS
    A1 = 'assets/personajes/maestros/a1.png'
    A2 = 'assets/personajes/maestros/a2.png'
    A3 = 'assets/personajes/maestros/a3.png'
    A4 = 'assets/personajes/maestros/a4.png'
    A5 = 'assets/personajes/maestros/a5.png'
    B1 = 'assets/personajes/maestros/b1.png'
    B2 = 'assets/personajes/maestros/b2.png'
    B3 = 'assets/personajes/maestros/b3.png'
    B4 = 'assets/personajes/maestros/b4.png'
    B5 = 'assets/personajes/maestros/b5.png'
    C1 = 'assets/personajes/maestros/c1.png'
    C2 = 'assets/personajes/maestros/c2.png'
    C3 = 'assets/personajes/maestros/c3.png'
    C4 = 'assets/personajes/maestros/c4.png'
    C5 = 'assets/personajes/maestros/c5.png'
    D1 = 'assets/personajes/maestros/d1.png'
    D2 = 'assets/personajes/maestros/d2.png'
    D3 = 'assets/personajes/maestros/d3.png'
    D4 = 'assets/personajes/maestros/d4.png'
    D5 = 'assets/personajes/maestros/d5.png'
    E1 = 'assets/personajes/maestros/e1.png'
    E2 = 'assets/personajes/maestros/e2.png'
    E3 = 'assets/personajes/maestros/e3.png'
    E4 = 'assets/personajes/maestros/e4.png'
    E5 = 'assets/personajes/maestros/e5.png'

    # POKEMONES
    BULBASOR1 = 'assets/pokemones/bulbasur01.png'
    BULBASOR2 = 'assets/pokemones/bulbasur02.png'
    BULBASOR3 = 'assets/pokemones/bulbasur03.png'
    CHARMANDER1 = 'assets/pokemones/charmander01.png'
    CHARMANDER2 = 'assets/pokemones/charmander02.png'
    CHARMANDER3 = 'assets/pokemones/charmander03.png'
    GATO1 = 'assets/pokemones/gato01.png'
    GATO2 = 'assets/pokemones/gato02.png'
    GATO3 = 'assets/pokemones/gato03.png'
    GATO4 = 'assets/pokemones/gato04.png'
    GUSANITO1 = 'assets/pokemones/gusanito01.png'
    GUSANITO2 = 'assets/pokemones/gusanito02.png'
    GUSANITO3 = 'assets/pokemones/gusanito03.png'
    MONSTRUO1 = 'assets/pokemones/monstruo01.png'
    MONSTRUO2 = 'assets/pokemones/monstruo02.png'
    MONSTRUO3 = 'assets/pokemones/monstruo03.png'
    PAJARITO1 = 'assets/pokemones/pajarito01.png'
    PAJARITO2 = 'assets/pokemones/pajarito02.png'
    PAJARITO3 = 'assets/pokemones/pajarito03.png'
    PEPPAPIG1 = 'assets/pokemones/peppapig01.png'
    PEPPAPIG2 = 'assets/pokemones/peppapig02.png'
    PEZ1 = 'assets/pokemones/pez01.png'
    PEZ2 = 'assets/pokemones/pez02.png'
    PEZ3 = 'assets/pokemones/pez03.png'
    PIKACHU1 = 'assets/pokemones/pikachu02.png'
    PIKACHU2 = 'assets/pokemones/pikachu03.png'
    RATOIDE1 = 'assets/pokemones/ratoide02.png'
    RATOIDE2 = 'assets/pokemones/ratoide03.png'
    SAPO1 = 'assets/pokemones/sapo01.png'
    SAPO2 = 'assets/pokemones/sapo02.png'
    SAPO3 = 'assets/pokemones/sapo03.png'
    VAMO1 = 'assets/pokemones/vamoacalmarno01.png'
    VAMO2 = 'assets/pokemones/vamoacalmarno02.png'
    VAMO3 = 'assets/pokemones/vamoacalmarno03.png'

    # RELIEVES
    AGUA = 'assets/relieves/agua.png'
    ARENA = 'assets/relieves/arena.png'
    PASTO = 'assets/relieves/pasto.png'
    TIERRA = 'assets/relieves/tierra.png'